= Docker image for MuleSoft's Anypoint CLI

A link:Dockerfile[Docker image definition] packaging MuleSoft's https://docs.mulesoft.com/runtime-manager/anypoint-platform-cli[Anypoint CLI] on top of a Node base image.

== Availability

The resulting Docker image is available from https://hub.docker.com/r/integrational/anypoint-cli[Docker Hub] as `integrational/anypoint-cli`.

The version of the Docker image is always that of the packaged Anypoint CLI. E.g., `integrational/anypoint-cli:3.0.0` is for Anypoint CLI `3.0.0`.

There is no `latest` Docker image.

== Usage

=== Simple usage

Simple interactive usage:

[source, bash]
----
docker run --rm -it integrational/anypoint-cli:3.0.0 --username=user --password=pwd
----

Simple usage to execute a CLI command, e.g. `api-mgr api list -o json` against the `Staging` environment:

[source, bash]
----
docker run --rm -it integrational/anypoint-cli:3.0.0 --username=user --password=pwd --environment=Staging api-mgr api list -o json
----

=== Recommended usage

In `.bashrc` or similar, define an alias for running the Docker container:

[source, bash]
----
alias anypoint-cli='docker run --rm --name anypoint-cli -it -e ANYPOINT_USERNAME="$(echo $ANYPOINT_USERNAME)" -e ANYPOINT_PASSWORD="$(echo $ANYPOINT_PASSWORD)" integrational/anypoint-cli:3.0.0'
----

and define the variables CLI uses for authentication (these can also be re-defined in the shell):

[source, bash]
----
export ANYPOINT_USERNAME=user
export ANYPOINT_PASSWORD=pwd
----

Then, for interactive usage:

[source, bash]
----
anypoint-cli
----

Or, to execute the above CLI command against the `Staging` environment:

[source, bash]
----
anypoint-cli --environment=Staging api-mgr api list -o json
----
